sudo: required
dist: trusty
language: node_js
node_js:
- 8.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: latest
cache:
  directories:
  - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  global:
  - CXX=g++-4.8
  - secure: L6s1nS9OJP+eVEvhqZyhQWCruklBzQQeXqHtRyG7eb1dPXCPYX4bJfWmRYCqwlyfQpYbg1xaTsUZY5jmain5nZTK9JbUDdqA0xRC3H8y2aTUCKvteG6Tw6UwiewzUcECEkyaPV8sUybHJDD7noSNnJ15Lp8l8NAFPAXG7yrEnjx+zOd7hDd9CjF9plafvHey4CSV1NzMoFfB4Av3F5jhyupaOufa5N6KxNsHi7M7qxSzPwau+b/y1QMKVlteA0EcEz9732BCpJjOeINYSqrsbyMhnJROvF3VVqOKcRRGtj+MpX9kxB9znVOwjIMl5sOM1UIJlgDhjLa8g10mLoBEDz4v6jEnIi5cuEEKElhjtEMCo0u+fn2acH77N3AtG8gXBRhq8MvqxpLQV38om2xXRgcLQjI0TflgQ/Wm29Y6jPKU+G+m2lpcf0LKC6UUIh2k5RKYF7qEYu5ajSz3oGn0xow3DkmOx6beFUmD+qN1q+EctW22KVyz+6vyyK8HJ434r2EbonspfZbgkfBOmOnPb3SryHpOFi4+WX9ebUrlzw6kr8O6iJQQoC/euUc0cC2foQdnOwmvCaIE2I5jSC6nACTZ1F/qs+KBzAZFZInLHirRAsVuzct1Sa+hoMS1FHpIGAVz3qJ3Ha61jwtNoELg/W3YbqHtCuOBL1F/77vv6+U=
matrix:
  fast_finish: true
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
- "$(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh"
install:
- "$(npm root -g)/pr-bumper/.travis/maybe-install.sh"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- "$(npm root -g)/pr-bumper/.travis/maybe-test.sh"
- ".travis/maybe-check-coverage.sh"
- ".travis/maybe-bump-version.sh"
after_success:
- ".travis/maybe-publish-coverage.sh"
- ".travis/maybe-publish-gh-pages.sh"
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: ib2DvN4wHZXncxVpFKBSV5sUvtfoUCxlYc5qQWPUxOfUIL8+9ohnsd55ZTdjl5h9WnYDLgvEef87GO6TZU6Hr1jWPkX07ZUQ9VlWb+DmMEPxG8OsvqG+xhU00N8TmGNutcIDVcSLCRd5QVRtufJBN8mpLuN7ihqo5JGNajJXccVqTqa9lki7H2/47H21LGuw1I/90k7nkTo/VPsYrESsMRgw2HDBhs8qL8QI25gdGqsWpEJIGqL/bWs2G3gxqG32RKwZnATkmWU09rF5hlke+EelfdfIOBTBAoilamUP+E7tlBPo+mhQwa9xG8CUNu125Keyoodps2/+HHzKyCwPLG7ITlFR0+bpjvPObkT5OB36ZVAbGMZBZsKvW6ISvepncGSHMEycVTMcTyrG9APDdbIZtevjtgL3PUx2g9YJ+0VO/gCiHnD+YPRtR6vANa2ZBON6iDXPsoLiusI1US4+sty1DWJJOPCci+21gbcHqjvvzu3VLBK8FFUfEySBK+cgwlDxnRlYl2fcPUFDoqq4XTm6So2ic8YyRUJoZBHUSCVmC3xjmiNCKgT6oym2hkYrYiDlkjE/aUXXvaEg+0SVSGJi/lhLeVfzQ3kt61OmVnGB2JTczNYCH6g4vQuy8iDfyiBVh6V3lno5QzV1S3ySVtID+/dsVtTBObnjcxSF7p8=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: 8.6.0
    tags: true
after_deploy:
- "$(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh"
notifications:
  slack:
    secure: YFn9p2YZAOh/o0gPBCDW5t3QvkBF5q7osPXjopbwPNFIWswcwdesBxHroUpkLuarYB6KqYFp+beo1SIjdnhxcXL8hcE1vpKb4gCj7/dn7Q54m1D1Ti2CXzn98k6o3ZZIYeSVynsZ4upi0D/uca4t3UGgyKMUWWXIVvvnaq50mQLmCY2ujKckL6nLH0ia42PhisdWsbTFX+xcLKsNNSgjzNgGmztybuUbxQ78Y01o9LDw0XjXs9fetGhJdz8A7sY6EBvOzS+zb1r/eKxXyzEYt5O/34vIUA2oo26vP9OP1a1HRYu7ba+Kfx2qya0FWgwpI8XkHqhJTV+JuO78nPr6dVdN735xkSjuZcorWI8jUbbE45gFVAzEuQKluuUim3uo8FV8mdnwYzDXgpoKT5y5Wts3jF101s88oDZ3HG6FeGZDJGGRl0HygGVE1P50FuSvCyzavWiTdi5gxd+crilIKIh+FzpGxwASY2p/eAZ8cQG8fJMGTbvq8L0W8k/QNnXi1BtzftT8l3TJE2WTAhgklkp9CYUTz/6znvJnEIxr7KfrBnYAjL+b8HLyB7BLsPSzQ879t07F/u73vJGjKyCVOnG4ZZU0ZsbSJS4QaTb81vq6VFk7OITLUTI56OaoBpBxJZ9AtzaSW2HZ8gPrrNEEProroSMoT11Ai2NMeKrTyXQ=
